### ISSUE TITLE
Which feature map do you use for training?

### ISSUE THREAD

**Issue by mathjihun** [needylove/OrdinalEntropy#1]
There are a total of four encoding feature maps in the NeWCRFs model. Which feature map should be used to calculate the loss? When I tried, NaN loss occurred during training with the third and fourth encoding feature maps. I want to know the reason for this. If there is a slightly different experimental environment, batch size is set to 2 due to memory issues.

**Comment by needylove** [comment]
Hi, we use the feature map nearest to the output. For the NaN, it may come from the tightness part, i.e. if _features equal to _features_center, then, the  NaN values will occur. In this case, every feature is its own center and the tightness part is no need anymore.

**Comment by mathjihun** [comment]
![20230306_150050](https://user-images.githubusercontent.com/87381172/223030874-2536137b-848d-422c-9a96-7a074b48a03e.png)
Thank you for the response. So, can I modify NewCRFDepth.py in the NeWCRFs code as shown in the picture and use it? I want to know if it's correct to use the final feature map based on the encoder, feats[3].

**Comment by needylove** [comment]
We use the final feature map based on the decoder, i.e. e0 in your picture. Yet, I think it's ok to try feats[3]

**Comment by mathjihun** [comment]
Thank you for the response. It was very helpful.
