### ISSUE TITLE
Question about Equation (9)

### ISSUE THREAD

**Issue by mathjihun** [needylove/OrdinalEntropy#5]
Hello, I have been trying to utilize your paper for monocular depth estimation, and I have some doubts about Equation (9) in the process, as it seems slightly different from what I understood from the code.

![image](https://github.com/needylove/OrdinalEntropy/assets/87381172/867b2fbe-8f42-4ab5-b602-eb097b46590e)
![image](https://github.com/needylove/OrdinalEntropy/assets/87381172/ba06bca6-9d27-4b3e-aad7-211c8364da2e)

In the paper, N_b is described as the batch size, but when I look at the code for the tightness part, the batch size doesn't appear to be used when calculating the average for each feature and feature center. In my opinion, it should be based on the number of features, or in other words, the number of valid depth values. Could you please confirm if my understanding is correct?

I appreciate your always helpful responses.

**Comment by needylove** [comment]
Hi, your understanding is correct. Eq 9 is correct under the image-wise prediction tasks, where the number of features equals the batch size, and it should be generalized to include dense prediction tasks like depth estimation.

**Comment by mathjihun** [comment]
Thank you so much for your response. It was incredibly helpful.
