### ISSUE TITLE
Can you provide the parameters for the best model in monocular depth estimation?

### ISSUE THREAD

**Issue by mathjihun** [needylove/OrdinalEntropy#6]
Hello. I am writing to inquire if it is possible to obtain the parameters for the best model of NeWCRFs used in the monocular depth estimation experiments in your paper. Could you please provide them?

Thank you.

**Comment by needylove** [comment]
Hi, the hyper-parameters are set the same as the NeWCRF, and the trade-off parameters lambda_t and lambda_d are both set to 1. If you want the trained model, I can hardly find the original one as it is already one year past

**Comment by mathjihun** [comment]
Thank you for answering me.
